src/WebApp/Pages/AboutUs.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class AboutUs : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

src/WebApp/Pages/BankAccountInputting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Models.Identity;
using WebApp.Models.Payment;
using WebApp.Models.Subscription;
using WebApp.Services.Payment;
using Microsoft.AspNetCore.Http.Headers;

namespace WebApp.Pages
{
    public class BankAccountInputtingModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IPaymentService _paymentService;
        private static string Referer;
        public BankAccountInputtingModel(UserManager<ApplicationUser> userManager, IPaymentService paymentService)
        {
            _userManager = userManager;
            _paymentService = paymentService;

        }
        public async Task<IActionResult> OnPostAddBankAccountAsync(string number, string refererLink)
        {
            var userId = (await _userManager.GetUserAsync(User)).UserId;


            await _paymentService.AddBankAccount(new BankAccountModel()
            {
                UserId = userId,
                Number = number
            });
            return Redirect(refererLink);
        }
        public async Task<IActionResult> OnGetAsync()
        {
            var userId = (await _userManager.GetUserAsync(User)).UserId;
            RequestHeaders header = Request.GetTypedHeaders();
            Uri uriReferer = header.Referer;
            if (uriReferer == null)
            {
                return RedirectToPage("Index");
            }
            else
            {
                ViewData["Referer"] = uriReferer.ToString();
            }
            return Page();
        }
    }
}

src/WebApp/Pages/CompanyProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Models;
using WebApp.Models.Developer;
using WebApp.Models.Identity;
using WebApp.Models.Subscription;
using WebApp.Services;
using WebApp.Services.Developer;

namespace WebApp.Pages
{
    public class CompanyProfile : PageModel
    {
        private readonly IDeveloperService _developerService;
        private readonly IServiceProvider _serviceProvider;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public CompanyProfile(IDeveloperService developerService, 
            IServiceProvider serviceProvider, 
            SignInManager<ApplicationUser> signInManager, 
            UserManager<ApplicationUser> userManager)
        {
            _developerService = developerService;
            _serviceProvider = serviceProvider;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public CompanyModel CompanyModel { get; private set; }

        public async Task<IActionResult> OnPostFollowAsync(int userId, int subscribedToId, TypeOfSubscription typeOfSubscription)
        {
            var handler = new SubscribeHandler(_serviceProvider);
            await handler.Follow(userId, subscribedToId, typeOfSubscription);
            return Redirect($"/CompanyProfile?id={subscribedToId}");
        }

        public async Task<IActionResult> OnPostSubscribeAsync(int subscribedToId, int userId, bool isBasic, bool isImproved, bool isMax, TypeOfSubscription typeOfSubscription)
        {
            var handler = new SubscribeHandler(_serviceProvider);
            await handler.Subscribe(userId, subscribedToId, isBasic, isImproved, isMax, typeOfSubscription);
            return Redirect($"/CompanyProfile?id={subscribedToId}");
        }

        public async Task<ActionResult> OnGetAsync(int id)
        {
            CompanyModel = await _developerService.GetCompany(id);
            
            if (CompanyModel is null)
                return NotFound();

            CompanyModel.Tags = await _developerService.GetTags(CompanyModel) ?? new List<TagModel>();
            CompanyModel.Users = await _developerService.GetCompanyUsers(id) ?? new List<UserModel>();
            CompanyModel.Projects = await _developerService.GetCompanyProjects(id) ?? new List<ProjectModel>();
            
            return Page();
        }

        public async Task<bool> CheckAccess(CompanyModel company)
        {
            if (!_signInManager.IsSignedIn(User))
                return false;

            var userId = (await _userManager.GetUserAsync(User)).UserId;
            
            var companyUsersIds = (await _developerService.GetCompanyUsers(company.Id))
                .Select(u => u.Id)
                .ToList();
            
            return companyUsersIds.Contains(userId);
        }
    }
}

src/WebApp/Pages/CompanySettings.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.DTOs;
using WebApp.Models.Developer;
using WebApp.Models.Files;
using WebApp.Models.Identity;
using WebApp.Services.Developer;
using WebApp.Services.Files;
using WebApp.Services.Payment;

namespace WebApp.Pages
{
    public class CompanySettings : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IDeveloperService _developerService;
        private readonly IPaymentService _paymentService;
        private readonly IFileService _fileService;
        private readonly IWebHostEnvironment _appEnvironment;

        public CompanySettings(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IDeveloperService developerService, IPaymentService paymentService, IFileService fileService, IWebHostEnvironment appEnvironment)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _developerService = developerService;
            _paymentService = paymentService;
            _fileService = fileService;
            _appEnvironment = appEnvironment;
        }

        public class InputModel
        {
            [Display(Name = "Name")]
            public string Name { get; set; }
            
            [Display(Name = "Add user")]
            public int NewUserId { get; set; }
            
            [Display(Name = "Coordinates")]
            public string Coordinates { get; set; }
        }
        
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        
        [BindProperty]
        public InputModel Input { get; set; }
        
        [BindProperty]
        public int CompanyId { get; set; }
        
        [Display(Name = "Avatar")]
        [BindProperty]
        public IFormFile Avatar { get; set; }
        
        public string AvatarPath { get; set; }
        
        public string StatusMessage { get; set; }
        
        private async Task LoadAsync(CompanyModel company)
        {
            var name = company.Name;
            AvatarPath = (await _fileService.GetAvatar(company.Id, CreatorType.Company)).Path;
            CompanyId = company.Id;
            Latitude = company.Latitude;
            Longitude = company.Longitude;

            Input = new InputModel
            {
                Name = name,
                Coordinates = $"{company.Latitude} {company.Longitude}"
            };
        }
        
        public async Task<IActionResult> OnGetAsync(int id)
        {
            var company = await _developerService.GetCompany(id);
            var user = await _userManager.GetUserAsync(User);

            if (company is null)
                return NotFound();

            if (user is null)
                return Redirect("/Identity/Account/Login");

            if (!(await _developerService.GetCompanyUsers(id)).Select(u => u.Id).Contains(user.UserId))
                return Forbid();
            
            await LoadAsync(company);
            return Page();
        }
        
        public async Task<IActionResult> OnPostAsync()
        {
            var id = CompanyId;
            var company = await _developerService.GetCompany(id);
            var user = await _userManager.GetUserAsync(User);
            
            if (company is null)
                return NotFound();

            if (user is null)
                return Redirect("/Identity/Account/Login");

            var companyUsersIds = (await _developerService.GetCompanyUsers(id))
                .Select(u => u.Id)
                .ToList();
            if (!companyUsersIds.Contains(user.UserId))
                return Forbid();
            
            if (!ModelState.IsValid)
            {
                await LoadAsync(company);
                return Page();
            }

            var name = company.Name;
            if (Input.Name != name)
            {
                await _developerService.UpdateCompanyName(new CompanyModel {Id = company.Id, Name = Input.Name});
            }

            if (Input.NewUserId > 0 && !companyUsersIds.Contains(Input.NewUserId))
            {
                await _developerService.AddUserToCompany(Input.NewUserId, company.Id);
            }

            if (!string.IsNullOrEmpty(Input.Coordinates))
            {
                var coordinates = Input.Coordinates.Replace(".", ",").Split(" ");
                var latitudeParseResult = decimal.TryParse(coordinates[0], out var latitude);
                var longitudeParseResult = decimal.TryParse(coordinates[1], out var longitude);

                if (latitudeParseResult && longitudeParseResult)
                {
                    await _developerService.UpdateCoordinates(new CoordinatesDto
                    {
                        CompanyId = company.Id,
                        Latitude = latitude,
                        Longitude = longitude
                    });
                }
            }
            
            if (Avatar is {ContentType: "image/jpeg" or "image/png"})
            {
                var avatar = new AvatarModel
                {
                    CreatorId = company.Id,
                    CreatorType = CreatorType.Company,
                    Name = $"{company.Id}_{Avatar.FileName}"
                };
                
                
                var path = $"/avatars/{avatar.Name}";
                await using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await Avatar.CopyToAsync(fileStream);
                }

                await _fileService.CreateAvatar(avatar);
            }
            
            await _signInManager.RefreshSignInAsync(user);
            StatusMessage = "Your profile has been updated";
            return Redirect($"/CompanySettings?id={id}");
        }
    }
}

src/WebApp/Pages/CreateCompany.cshtml.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Models.Developer;
using WebApp.Models.Files;
using WebApp.Models.Identity;
using WebApp.Services.Developer;
using WebApp.Services.Files;
using WebApp.Services.Posts;

namespace WebApp.Pages
{
    public class CompanyForm
    {
        public string Name { get; set; }
        public int UserId { get; set; }
    }
    
    public class CreateCompany : PageModel
    {
        private readonly IDeveloperService _developerService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IFileService _fileService;
        private readonly IWebHostEnvironment _appEnvironment;

        public CreateCompany(IDeveloperService developerService, SignInManager<ApplicationUser> signInManager, IFileService fileService, IWebHostEnvironment appEnvironment, UserManager<ApplicationUser> userManager)
        {
            _developerService = developerService;
            _signInManager = signInManager;
            _fileService = fileService;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }

        public ActionResult OnGet()
        {
            return Page();
        }

        public async Task<ActionResult> OnPostAsync(CompanyForm companyForm, IFormFile avatar)
        {
            if (!_signInManager.IsSignedIn(User))
                return Forbid();
            
            companyForm.UserId = (await _userManager.GetUserAsync(User)).UserId;
            var message = await _developerService.CreateCompany(companyForm);
            
            if (!string.IsNullOrEmpty(message))
                return BadRequest(message);

            var companyId = (await _developerService.GetCompany(companyForm.Name)).Id;

            if (avatar is not null)
            {
                var path = $"/avatars/{companyForm.Name}.{avatar.FileName.Split(".").Last()}";
                await using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await avatar.CopyToAsync(fileStream);
                }

                await _fileService.CreateAvatar(new AvatarModel()
                {
                    CreatorId = companyId,
                    Name = $"{companyForm.Name}.{avatar.FileName.Split(".").Last()}",
                    CreatorType = CreatorType.Company
                });
            }
            
            return Redirect($"/CompanyProfile?id={companyId}");
        }
    }
}

src/WebApp/Pages/Creators.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApp.Models;
using WebApp.Models.Developer;
using WebApp.Services;
using WebApp.Services.Developer;

namespace WebApp.Pages
{
    public class Creators : PageModel
    {
        private readonly IDeveloperService _developerService;

        public Creators(IDeveloperService developerService)
        {
            _developerService = developerService;
        }

        public List<ICreator> CreatorModels { get; private set; }

        public async Task<ActionResult> OnGetAsync(string needUsers, 
            string needProjects, 
            string needCompanies, 
            string searchString,
            string sortOption)
        {
            CreatorModels = new List<ICreator>();
            
            var needAll = needUsers is null &&
                          needProjects is null &&
                          needCompanies is null;
            
            if (needUsers == "on" || needAll)
                CreatorModels.AddRange(await SearchUsers(searchString));
            
            if (needProjects == "on" || needAll)
                CreatorModels.AddRange(await SearchProjects(searchString));
            
            if (needCompanies == "on" || needAll)
                CreatorModels.AddRange(await SearchCompanies(searchString));
            
            if (!CreatorModels.Any())
                return Page();
            
            if (sortOption != null)
                Sort(sortOption);

            foreach (var creator in CreatorModels)
            {
                creator.Tags = await _developerService.GetTags(creator);

                switch (creator)
                {
                    case UserModel user:
                        user.Companies = await _developerService.GetUserCompanies(user.Id);
                        break;
                    case ProjectModel project:
                        project.Company = await _developerService.GetProjectCompany(project.Id);
                        break;
                }
            }
            
            return Page();
        }

        private void Sort(string sortOption)
        {
            CreatorModels = sortOption switch
            {
                "byAlphabet" => CreatorModels.OrderBy(c => c.Name).ToList(),
                _ => CreatorModels.OrderBy(c => c.Id).ToList()
            };
        }
        
        private async Task<IEnumerable<UserModel>> SearchUsers(string searchString)
        {
            if (string.IsNullOrEmpty(searchString))
                return await _developerService.GetUsers() ?? new List<UserModel>();

            return await _developerService.GetUsersByName(searchString) ?? new List<UserModel>();
        }

        private async Task<IEnumerable<ProjectModel>> SearchProjects(string searchString)
        {
            if (string.IsNullOrEmpty(searchString))
                return await _developerService.GetProjects() ?? new List<ProjectModel>();

            return await _developerService.GetProjectsByName(searchString) ?? new List<ProjectModel>();
        }

        private async Task<IEnumerable<CompanyModel>> SearchCompanies(string searchString)
        {
            if (string.IsNullOrEmpty(searchString))
                return await _developerService.GetCompanies() ?? new List<CompanyModel>();

            return await _developerService.GetCompaniesByName(searchString) ?? new List<CompanyModel>();
        }
    }
}

src/WebApp/Pages/BankAccountInputting.cshtml
@page
@model WebApp.Pages.BankAccountInputtingModel
@{
    ViewData["Title"] = "Bank Account";
}

<div class="credit-card container">
    <form method="post">
        <div class="row credit-info">
            <div class="col-auto">
                <input name="number" type="text" placeholder="xxxx xxxx xxxx xxxx" class="input-credit-card form-control"/>
            </div>
            <div class="col-auto">
                <input name="refererLink" type="hidden" value="@ViewData["Referer"]"/>
                <input type="submit" asp-page-handler="AddBankAccount" class="btn btn-add-card"/>
            </div>
        </div>
    </form>
</div>

src/WebApp/Pages/CompanyProfile.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using WebApp.Models.Identity
@model WebApp.Pages.CompanyProfile
@{
    ViewData["Title"] = "Company Profile";
}

@inject SignInManager<ApplicationUser> _signInManager
@inject UserManager<ApplicationUser> _userManager

<div class="container">
    <div class="row row-cols-2">
        <div class="col">
            @await Html.PartialAsync("Shared/_CreatorPreviewPartial", Model.CompanyModel)
        </div>
        <div class="col" style="margin-top: 10px">
            @if (await Model.CheckAccess(Model.CompanyModel))
            {
                <a asp-page="/CompanySettings" asp-route-id="@Model.CompanyModel.Id" class="btn btn-main" style="max-width: 100px">Edit</a>
            }
            <div class="row row-cols-4">
                @foreach (var user in Model.CompanyModel.Users)
                {
                    <div class="col-auto">
                        @await Html.PartialAsync("Shared/_UserMiniPreviewPartial", user)
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@if (Model.CompanyModel.Latitude > 0 && Model.CompanyModel.Longitude > 0)
{
    <div class="container">
        <p>
            <a class="btn btn-main" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                Office
            </a>
        </p>
        <div class="collapse" id="collapseExample">
            <div id="map" class="card card-body" style="height: 800px;"></div>
        </div>
    </div>
}

<div class="projects-slider container">
    @foreach (var project in Model.CompanyModel.Projects)
    {
        @await Html.PartialAsync("Shared/_ProjectMiniPreviewPartial", project)
    }
</div>

@section Scripts
{
    <script src="https://api-maps.yandex.ru/2.1/?apikey=ed9ee632-4f57-4dd1-ad11-59fae15159cd&lang=ru_RU" type="text/javascript"></script>
    <script type="text/javascript">
        ymaps.ready(init);
        function init(){
            let latitude = parseFloat("@Model.CompanyModel.Latitude".replace(",", "."));
            let longitude = parseFloat("@Model.CompanyModel.Longitude".replace(",", "."));
            
            let myMap = new ymaps.Map("map", {
                center: [latitude, longitude],
                zoom: 11
            });
    
            let myGeoObject = new ymaps.Placemark([latitude, longitude]);
    
            let myClusterer = new ymaps.Clusterer(
              {clusterDisableClickZoom: false}
            );
            myClusterer.add(myGeoObject);
            myMap.geoObjects.add(myClusterer);
        }
    </script>
}

src/WebApp/Pages/CompanySettings.cshtml
@page
@model WebApp.Pages.CompanySettings
@{
    ViewData["Title"] = "Company Settings";
}

<div class="container">
    <partial name="_StatusMessage" model="Model.StatusMessage" />
    <div class="row">
        <div class="col-md-6">
            <form id="company-form" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="CompanyId" type="hidden"/>
                <div class="form-group">
                    <label asp-for="Input.NewUserId"></label>
                    <input asp-for="Input.NewUserId" class="form-control"/>
                    <span asp-validation-for="Input.NewUserId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.Name"></label>
                    <input asp-for="Input.Name" class="form-control"/>
                    <span asp-validation-for="Input.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.Coordinates"></label>
                    <input asp-for="Input.Coordinates" class="form-control"/>
                    <span asp-validation-for="Input.Coordinates" class="text-danger"></span>
                    <p>
                        <a class="btn btn-main" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Choose a location
                        </a>
                    </p>
                    <div class="collapse" id="collapseExample">
                        <div id="map" class="card card-body" style="height: 500px;"></div>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Avatar"></label>
                    <div>
                        @if (Model.AvatarPath != null)
                        {
                            <img src="/@Model.AvatarPath" alt="avatar" style="max-width: 300px">
                        }
                    </div>
                    <div class="input-group mb-3" style="max-width: 400px; margin-top: 10px">
                        <div class="custom-file">
                            <input asp-for="Avatar" type="file" class="custom-file-input" name="avatar" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                            <span asp-validation-for="Avatar" class="text-danger"></span>
                            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                        </div>
                    </div>
                </div>
                <button id="update-company-button" type="submit" class="btn btn-primary" style="margin-bottom: 10px">Save</button>
            </form>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="https://api-maps.yandex.ru/2.1/?apikey=ed9ee632-4f57-4dd1-ad11-59fae15159cd&lang=ru_RU" type="text/javascript"></script>
    <script type="text/javascript">
        ymaps.ready(init);
        function init(){
            let latitude = parseFloat("@Model.Latitude".replace(",", "."));
            let longitude = parseFloat("@Model.Longitude".replace(",", "."));
            
            let myMap = new ymaps.Map("map", {
                center: [latitude, longitude],
                zoom: 11
            });
    
            let myGeoObject = new ymaps.Placemark([latitude, longitude]);
    
            let myClusterer = new ymaps.Clusterer(
              {clusterDisableClickZoom: false}
            );
            myClusterer.add(myGeoObject);
            myMap.geoObjects.add(myClusterer);
            
            myMap.events.add('click', function (e) {
                let coords = String(e.get("coords"));
                let result = coords.split(',')[0] + " " + coords.split(',')[1];
                document.getElementById("Input_Coordinates").value = result;
            });
        }
    </script>
}

src/WebApp/Pages/CreateCompany.cshtml
@page
@model WebApp.Pages.CreateCompany
@{
    ViewData["Title"] = "Create Company";
}

<div class="container" style="margin-top: 100px">
    <form method="POST" enctype="multipart/form-data">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-sizing-default">Name</span>
          </div>
          <input type="text" name="name" required>
        </div>
        <!--<div>
            <label>Name</label>
            <input type="text" name="name" required>
        </div>-->
        <div class="input-group mb-3" style="max-width: 400px">
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="avatar" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
          </div>
        </div>
        <!--<div>
            <input type="file" name="avatar">
        </div>-->
        <button type="submit" class="btn btn-main">Create</button>
    </form>
</div>

src/WebApp/Pages/CreateProject.cshtml
@page
@model WebApp.Pages.CreateProject
@{
    ViewData["Title"] = "Create Project";
}

<div class="container" style="margin-top: 100px">
    <form method="POST" enctype="multipart/form-data">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">Name</span>
            </div>
            <input type="text" name="name" required>
        </div>
        <div>
            <label>Company: </label>
            @foreach (var company in Model.UserCompanies)
            {
                <label>@company.Name</label>
                <input type="radio" name="companyId" value="@company.Id">
            }
        </div>
        <div class="input-group mb-3" style="max-width: 400px">
            <div class="custom-file">
                <input type="file" class="custom-file-input" name="avatar" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
            </div>
        </div>
        @*todo add tags*@
        <button type="submit" class="btn btn-main">Create</button>
    </form>
</div>

src/WebApp/Pages/Creators.cshtml
@page
@model WebApp.Pages.Creators
@{
    ViewData["Title"] = "Creators";
}

<div class="container-xl">
    <form method="get">
        <div class="container" style="padding-bottom: 10px;">
            <div class="row align-items-center">
                <div class="col-6" style="min-width: 300px">
                    <input type="text" name="searchString" placeholder="What are you searching for?" class="input-search form-control" autocomplete="off">
                </div>
                <div class="col-auto">
                    <button class="btn btn-search">Search</button>
                </div>
                <div class="round col-auto">
                    <input type="checkbox" name="needUsers" class="checkbox" id="checkbox-1">
                    <label for="checkbox-1" class="checkbox-label">Users</label>
                </div>
                <div class="round col-auto">
                    <input type="checkbox" name="needProjects" class="checkbox" id="checkbox-2">
                    <label for="checkbox-2" class="checkbox-label">Projects</label>
                </div>
                <div class="round col-auto">
                    <input type="checkbox" name="needCompanies" class="checkbox" id="checkbox-3">
                    <label for="checkbox-3" class="checkbox-label">Companies</label>
                </div>
            </div>
        </div>
    </form>
    
        <div class="row row-cols-2">
            @foreach (var creator in Model.CreatorModels)
            {
                @await Html.PartialAsync("Shared/_CreatorPreviewPartial", creator)
            }
        </div>
</div>

@section Scripts
{
    <script>
    let params = window
        .location
        .search
        .replace('?','')
        .split('&')
        .reduce(
            function(p, e){
                let a = e.split('=');
                p[decodeURIComponent(a[0])] = decodeURIComponent(a[1]);
                return p;
            },
            {}
        );
    
    window.onload = function () {
        if (params["searchString"].length > 0)
            document.getElementsByName("searchString")[0].setAttribute("value", params["searchString"]);
        
        if (params["needUsers"] === "on")
            document.getElementsByName("needUsers")[0].setAttribute("checked", "true");
        
        if (params["needProjects"] === "on")
            document.getElementsByName("needProjects")[0].setAttribute("checked", "true");
        
        if (params["needCompanies"] === "on")
            document.getElementsByName("needCompanies")[0].setAttribute("checked", "true");
    }
    </script>
}

src/WebApp/Pages/Feed.cshtml
@page
@model WebApp.Pages.Feed
@{
    ViewData["Title"] = "Feed";
}

@if (Model.PostModels is null || !Model.PostModels.Any())
{
    <div class="container" style="margin-top: 40px">
        <h3>There are no posts here yet</h3>
        <p>You are not subscribed to anyone...</p>
        <a class="btn btn-main" asp-area="" asp-page="/Creators" style="max-width:220px">Find creators</a>
    </div>
}
else
{
    <div class="container">
        @foreach (var post in Model.PostModels)
        {
            @await Html.PartialAsync("Shared/_PostPartial", post)
        }
    </div>
}

src/WebApp/Pages/FileDetails.cshtml
@page
@model WebApp.Pages.FileDetails
@{
    ViewData["Title"] = "File Details";
}

@section Scripts
{
    <script src="/js/highlight.js"></script>
    <script>hljs.highlightAll();</script>
}

@section Styles 
{
    <link rel="stylesheet" href="/css/highlight.css">
}

<pre>
    <code>
        @Model.Code
    </code>
</pre>